version: '3'

vars:
  TRANSLATOR_DIR: ./translator
  TIMER_DIR: ./timer

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================
  # Translator (Next.js)
  # ============================================================

  translator:dev:
    desc: Start translator dev server
    dir: '{{.TRANSLATOR_DIR}}'
    cmds:
      - npm run dev

  translator:build:
    desc: Build translator
    dir: '{{.TRANSLATOR_DIR}}'
    cmds:
      - npm run build

  translator:start:
    desc: Start translator production server
    dir: '{{.TRANSLATOR_DIR}}'
    cmds:
      - npm run start

  translator:lint:
    desc: Lint translator
    dir: '{{.TRANSLATOR_DIR}}'
    cmds:
      - npm run lint

  translator:install:
    desc: Install translator dependencies
    dir: '{{.TRANSLATOR_DIR}}'
    cmds:
      - npm install

  # ============================================================
  # Timer (Next.js)
  # ============================================================

  timer:dev:
    desc: Start timer dev server
    dir: '{{.TIMER_DIR}}'
    cmds:
      - npm run dev

  timer:build:
    desc: Build timer
    dir: '{{.TIMER_DIR}}'
    cmds:
      - npm run build

  timer:start:
    desc: Start timer production server
    dir: '{{.TIMER_DIR}}'
    cmds:
      - npm run start

  timer:lint:
    desc: Lint timer
    dir: '{{.TIMER_DIR}}'
    cmds:
      - npm run lint

  timer:install:
    desc: Install timer dependencies
    dir: '{{.TIMER_DIR}}'
    cmds:
      - npm install

  # ============================================================
  # All Apps
  # ============================================================

  install:
    desc: Install all dependencies
    cmds:
      - task: translator:install
      - task: timer:install

  build:
    desc: Build all apps
    cmds:
      - task: translator:build
      - task: timer:build

  lint:
    desc: Lint all apps
    cmds:
      - task: translator:lint
      - task: timer:lint
